export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_TO_WISH_CART = "ADD_TO_WISH_CART";
export const DELETE_FROM_WISH_CART = "DELETE_FROM_WISH_CART";
